---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgACb4aRoWZRYJ2pqP4Rg1iMOrn/iQ9ZebYLJx5DcXQgzdAayXod+C5fM5l/X4BJxMSO4buv370+7cr8b/SS7pJzbRKXSavb+WaoBgCnXUCbgnyeITq/czFbx9oNxPtkKk470EHneNxy7YspLvevVVBIIumYu99k+OrbFFVGvQ6G/RO45Nt3s78Ku1f1+9I1P/0sF5KcpIkiHuFHdJ1QUGFQJLSqU5KkvntOedfTYhIU9ohaPTvQERwPTgfVC4TOgzi0QALnWhWUZ/DqUHy6G7dQCEhDpIM5MQyn6IwTrc3GfuLYeWOwb6DMINND/k0o0dqfvRka9NEaUXuDNvD0QhXDdG0KnBfA353cnyyK67nZj+aGtgPXorq8AfzVvaOQ7lKOyw5AHTV2zvn74I4NeLp/AJuqmBdZslPHkpqmvk/4bbIhmyADhSWnBg/0qVzwyfauR25WrQsHMjLFlfGYe0WUh1gjrJgnCS6XfAnfcB+aaD15LA434TtbzLNfeKLxI9N+Aqpty7YsMp5/WuPvhYvQRuxGvY/6wfsi1twcx5EXpnvgSWUfhaCaj95lIAa+AtL/cDFU+Gv1aSyw6rjP2wD6maqE8QJXbTM7zhO652aeTE3Ip1oK1hXsdffL4L0FHmRbzsXGBpi0KfOg5lM7L3oh5pn9/7extbW02erqPW7K64MzxUvF9V9+Se8d6QjGMYWFmykHlLI3h0n9A8PdwrWp8KrazfEMcyKX
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
